### PR TITLE
ZIR-226: refactor keccak: reg aliasing and unified constraints

### PR DESCRIPTION
**Pull request by iddo-bentov**

### CODE REVIEW

**Comment by pdg744** [comment]
looks like the tests are passing now -- @jacobdweightman @shkoo can you take a look at this so we can get it landed?

**Comment by jacobdweightman** [comment]
Summary of circuit changes from `--emit=stats` comparing main vs this branch rebased on main:
* 334 -> 198 data columns (a 1.86x improvement from main, or 2.14x from the 425 columns we started with)
* 1261 -> 1185 total taps
* 84005 -> 11533 constraints (a 7.28x improvement from main)
* 47919 -> 19772 total operations in the validity taps function (a 2.42x improvement from main)
* 49 -> 60 seconds to compile with `--emit=stats` on my machine, (a 24% slowdown from main)

**Review by jacobdweightman — APPROVED** [review]
Given that the tests pass and the stats look so good, I'm going to rubber stamp this and give it a more thorough review independently as we head towards getting this audited.

**Comment by flaub** [comment]
I'm also interested in LoC changes for various codegen backends.

**Comment by iddo-bentov** [comment]
The "49 -> 60 seconds" slowdown might be because of the concatenate (and rotate) components using mux instead of field mult (after Nils merges his fix for mux eval of only the active arm it should make it faster).

**Pull request merged**
